### ISSUE TITLE
Registering a type or structure instead of just a format

### ISSUE THREAD

**Issue by damienleroux** [gcanti/tcomb-json-schema#13]
Hi gcanti,

I begin using tcomb-json-format. what do you think about registering a type or structure instead of just a format

Here is my use case:

```javascript

/**
 * Generate a tComb string type with a format limiting maxlength
 * @param {tComb.Num} maxLength
 */
function stringDynamic(maxLength: tComb.Num){
  return tComb.subtype(tComb.Str, function (s) {
    return s.length < maxLength;
  }, 'STRING' + maxLength);
}

//example
transform.registerType('string10', stringDynamic(10));

var TcombType = transform({
"type": "object",
  "properties": {
    "Name": {
      "type": "string10"
    }
});

```

Actually this allows the user to define is own types and structures and there then is no need to define the data "format" that might be redundant with the data "type".

Thank you

**Comment by gcanti** [comment]
Hi @damienleroux,
Seems a good idea, thanks. 
Do you want to send a PR or do I go for it?

**Comment by damienleroux** [comment]
I'll submit a PR asap. Thank you

**Comment by gcanti** [comment]
Released https://github.com/gcanti/tcomb-json-schema/releases/tag/v0.2.1
