### ISSUE TITLE
IE8 error with 'null' type

### ISSUE THREAD

**Issue by Joran182to** [gcanti/tcomb-json-schema#17]
Error "Expected identifier, string or number" caused by this line 110 from index.js: 
```
  null: function () {
    return util.Null;
  }
```
Seems like it's happened due to 'null' preserved keyword in IE8, so I changed this with:
```
  "null": function () {
    return util.Null;
  }
```

**Comment by gcanti** [comment]
Hi @Joran182to, thanks for reporting. Would you like to send a PR?

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-json-schema/releases/tag/v0.2.2
