### ISSUE TITLE
minItems and maxItems seems have no effect for `array`

### ISSUE THREAD

**Issue by WeweTom** [gcanti/tcomb-json-schema#18]
in the playground I typed json below , but have no effect 
```
{
  "type": "array",
  "minItems":2,
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "surname": {
        "type": "string"
      }
    },
    "required": ["name", "surname"]
  }
}
```

**Comment by gcanti** [comment]
Hi,

the playground is a bit outdated and supports only objects and lists (adding `minItems` would output a subtype of a list) however you've found a bug in the library!
Working on this... thanks for taking the time to report.

**Comment by gcanti** [comment]
Released a fix in https://github.com/gcanti/tcomb-json-schema/releases/tag/v0.2.3

**Comment by WeweTom** [comment]
great job !
