### ISSUE TITLE
Boolean rendering as text input rather than checkbox

### ISSUE THREAD

**Issue by rnewstead1** [gcanti/tcomb-json-schema#22]
I am using:

- tcomb-form v0.9.0
- tcomb-json-schema v0.3.0
- react v0.14.7

I am using the boolean example from the tcomb-json-schema playground to render a checkbox.

However the boolean gets rendered as a text input rather than a checkbox.

Code:
```
import React, {Component, PropTypes} from 'react';
import t from 'tcomb-form';
import transform from 'tcomb-json-schema';

const Form = t.form.Form;

const json = {
  "type": "object",
  "properties": {
    "username": {
      "type": "string"
    },
    "rememberMe": {
      "type": "boolean"
    }
  },
  "required": ["username"]
};

const schema = transform(json);

class MyForm extends Component {

  render() {
    return (
      <form>
        <Form ref="form" type={schema}/>
      </form>
    );
  }
}

export default MyForm;
```
Screenshot:
<img width="1131" alt="boolean-rendered-as-text-input" src="https://cloud.githubusercontent.com/assets/370785/13951599/f9bfa3ce-f029-11e5-8d73-faaece63f74e.png">

From debugging, it looks like `transform` is correctly identifying the boolean, but I can't work out why this is not getting rendered.

Is there some incompatibility between the versions I'm using? I noticed the playground is using an older version of tcomb-json-schema.

**Comment by gcanti** [comment]
Hi @rnewstead1,
may be relevant https://github.com/gcanti/tcomb-form/issues/303#issuecomment-189698990

**Comment by rnewstead1** [comment]
Thanks @gcanti. It looks like tcomb 2.7.0 is included from the templates. I've raised a PR to update this: https://github.com/gcanti/tcomb-form-templates-bootstrap/pull/6.

I'll let you know if this fixed the issue.

**Comment by gcanti** [comment]
Oh wow, you are right. Sorry for the inconvenience

**Comment by gcanti** [comment]
@rnewstead1 just published:

https://github.com/gcanti/tcomb-form-templates-bootstrap/releases/tag/v0.2.0
https://github.com/gcanti/tcomb-form/releases/tag/v0.9.1

should fix this issue

**Comment by rnewstead1** [comment]
Fixed! Thanks @gcanti

**Comment by gcanti** [comment]
Thanks to you for reporting
