### ISSUE TITLE
Maintaining this library

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-json-schema#27]
Hi @gcanti!

Thanks again for you excellent work on `tcomb` and related libraries. We really love to use them. We're interested in maintaining this library because we've been using our own forked code for a while. Are you interested in solving some issues and updating a little bit the code? Currently we moved the code to `prettier` code style, adopted ES6 features and solved a few issues that I cannot remember ATM.

Ping me if you want me to separate those things into different PRs or if you prefer us to keep doing the work in our own fork.

Best regards.

**Comment by gcanti** [comment]
Hi @alvaromb,

> Are you interested in solving some issues and updating a little bit the code?

Sure thing
