### ISSUE TITLE
support format property for string types

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-json-schema#6]
adding a `registerFormat` API

**Comment by gcanti** [comment]
@oliger good idea, thx! 
I added your API to the default export in order to avoid a breaking change

**Comment by gcanti** [comment]
Oops, soudain j'ai pensé: peut-être voulais vous faire une PR?
Dans ce cas, je suis désolé :-(

Giulio

**Comment by oliger** [comment]
> I added your API to the default export in order to avoid a breaking change

:+1: 

> Oops, soudain j'ai pensé: peut-être voulais vous faire une PR?
> Dans ce cas, je suis désolé :-(

No problem! :wink:

**Comment by ahdinosaur** [comment]
:+1:
