### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by gschrader** [gcanti/tcomb-json-schema#9]
I'm trying to hunt down an issue I'm having with my schema which seems to work just fine on the [playground](https://gcanti.github.io/resources/json-schema-to-tcomb/playground/playground.html) but not with the latest release. It seems like the playground was removed at 950a9fab8e1ae1a42ded2472d787b4f8b948847a.  Was there a reason it was removed?

**Comment by gcanti** [comment]
Hi @gschrader,
No particular reason, just one fewer thing to mantain.

**Comment by gschrader** [comment]
Fair enough, it's handy to paste in to test but I'll put together a throwaway project to test instead.

**Comment by gcanti** [comment]
If you need some help let me know, we could add some unit test to the repo.

Giulio
